### ISSUE TITLE
Unclear mmap call

### ISSUE THREAD

**Issue by Ravenslofty** [dholroyd/usbfs-device#1]
I've been running Clippy over your code, and it pointed out [this line](https://github.com/dholroyd/usbfs-device/blob/de27f8e762881fab508828b24aa8ed5e0e613991/src/lib.rs#L171) where you pass `PROT_READ | PROT_READ` to mmap. I haven't quite read the code enough to understand it, so did you mean `PROT_READ | PROT_WRITE`?

**Comment by Ravenslofty** [comment]
Speaking of which, `mmap` itself is never actually used.

**Comment by dholroyd** [comment]
Yeah, should probably be `PROT_READ | PROT_WRITE`.

This was added in anticipation of implementing usbfs zerocopy support, but the rest of the implementation is missing!

**Comment by Ravenslofty** [comment]
That sounds interesting; can you send me a link about it? I've been working
based on the [ckb-next](https://github.com/ckb-next/ckb-next) source code
(because I'm familiar with it), and that doesn't implement zero-copy USB.

**Comment by dholroyd** [comment]
https://lore.kernel.org/patchwork/patch/631458/

...if the buffers used for URBs are placed within memory allocated by `mmap()` against the device handle, it can be a win e.g. for bulk transfers where copying data kernel<->userspace might otherwise be significant.

I didn't actually get around to implementing bulk or isochronous, so this isn't wired up.

**Comment by dholroyd** [comment]
Also, I believe libusb already supports allocating memory for URBs this way.

**Comment by Ravenslofty** [comment]
Since this zero-copy support is already two years old, I'm tempted to use it for all types of URBs.

It's perhaps unnecessary for control/interrupt transfers, but I would rather not maintain two different methods of allocating URB memory, and since this has apparent performance advantages, I'd prefer using zero-copy alone.

**Comment by Ravenslofty** [comment]
Let's continue discussion about the URB backing storage in #3 instead.
